### ISSUE TITLE
Application Panes do not have a "close" button

### ISSUE THREAD

**Issue by walidabualafia** [OSC/bc_osc_matlab#25]
Hello! 

I've installed bc_osc_matlab in my OOD instance, but I am having trouble figuring out how to close panes?

For example, if I have Matlab running, and I go to `Apps` -> `Signal Analyzer`, the Signal Analyzer window will be overlayed on top of the Matlab window. There is no gui button to close the pane.

Is there anything that I can add to `template/script.sh.erb` to get GUI close button in xfce-panel?

Thanks! :)

**Comment by johrstrom** [comment]
I'll take a look.

**Comment by johrstrom** [comment]
What version of Matlab are you running? I was able to replicate the first time I did this, but after I maximized the window (The Signal analyzers menu) it started to work out of the box.

Just right click the panel item and maximize to see the buttons.  After that, it may just start showing it in the right spot for you as it did for me.
![image](https://github.com/OSC/bc_osc_matlab/assets/4874123/3a674e02-c83f-4707-a9c9-099639c81be8)

**Comment by walidabualafia** [comment]
@johrstrom, thank you for your quick and swift response. I am also using version 2023a.

Unfortunately, I'm unable to view the panel item. Here's what my view looks like (I blotted out some paths/files):
<img width="1470" alt="Screenshot 2024-01-11 at 11 26 14" src="https://github.com/OSC/bc_osc_matlab/assets/72840420/7146a7c2-b064-4318-a1ad-34b7b1a3bbb6">

Matlab seems to crash on startup as well, although the application runs perfectly...

My `template/script.sh.erb` looks like this (I only run on CPU nodes for now):
```
#!/usr/bin/env bash

# gpu = context.node_type.include?("vis") -%>

# Clean the environment
module purge

# Set working directory to home directory
cd "${HOME}"

#
# Launch Xfce Window Manager and Panel
#

(
  export SEND_256_COLORS_TO_REMOTE=1
  export XDG_CONFIG_HOME="<%= session.staged_root.join("config") %>"
  export XDG_DATA_HOME="<%= session.staged_root.join("share") %>"
  export XDG_CACHE_HOME="$(mktemp -d)"
  export $(dbus-launch)

  module restore
  set -x
  xfwm4 --compositor=off --daemon --sm-client-disable
  xsetroot -solid "#D3D3D3"
  xfsettingsd --sm-client-disable
  xfce4-panel --sm-client-disable
) &

#
# Start MATLAB
#

# Load the required environment
#module load xalt/latest
# Load the matlab module
module load <%= context.version %>

# Launch MATLAB
<%- if context.check_gpu.to_i == 1 -%>
#module load intel/16.0.3 virtualgl
module list
set -x
vglrun matlab -desktop -nosoftwareopengl
<%- else -%>
module list
set -x
matlab -desktop
<%- end -%>
```

Do you know why the panel is not popping up? I assume the lines responsible for xfce features are:
```
set -x
  xfwm4 --compositor=off --daemon --sm-client-disable
  xsetroot -solid "#D3D3D3"
  xfsettingsd --sm-client-disable
  xfce4-panel --sm-client-disable
```
Which I did not change from the default.

Thanks for your continued help and for your work on this wonderful app! :)

**Comment by johrstrom** [comment]
OK - I think I figured out what's going on for you.

For me, when I run this application (this is our production Matlab) I get this file `config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml` created by XFCE that must be the default.

This repository doesn't have this file because the defaults for me seem to work fine for this app. However, another app, I did have to update this file and use it in the app to override some defaults. I suggest you do the same.

The app that I had to do this on is `bc_osc_visit`.  The specific configuration you're looking for I think is `button_layout` and you can see it's default is `O|SHMC`. If you set it to an empty string - or remove it - I can replicate your issue. (open `xfce4-settings-manager` or `xfce4-settings-editor` to get a GUI to edit these configurations).

https://github.com/OSC/bc_osc_visit/blob/80be1e41208414163c572d8eb62c631a59841db2/template/config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml#L9

**Comment by walidabualafia** [comment]
Thanks for your response. Apologies for the delay, we got snowed in! :snowman:

Per your recommendation, I checked `xfce4-settings-manager` and found that `button_layout` is set to `O|SHMC` by default. I tried to explicitly copy the file and set it in `config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml` like you did with `bc_osc_visit`, but I still have the same issue.

Also, the app seems to place the Matlab portal in weird locations+sizes, and I cannot move it. I'm attaching some screenshots (paths and files blotted out):
<img width="1470" alt="Screenshot 2024-01-17 at 17 18 03" src="https://github.com/OSC/bc_osc_matlab/assets/72840420/21d11a9c-e154-416f-8ebf-d935918dbeb1">
<img width="1470" alt="Screenshot 2024-01-17 at 17 08 05" src="https://github.com/OSC/bc_osc_matlab/assets/72840420/ef486c9e-76a2-4960-a9c8-6496803d3fc2">

Whenever Matlab spins up, it creates a crash dump file. I looked at this dump, but seems completely unrelated to xfce, and more like a segfault caught in Matlab install itself. Matlab's error mode seems to be set to `continue`. Do you think this might have to do with it?

Thanks again for the support!

**Comment by johrstrom** [comment]
Yes there seems to be something more problematic going on.

I don't see any of the surrounding XFCE stuff - like the menu panel that shows up on the top of the screen.

Does an XFCE desktop work for you (without matlab, just the desktop)?

**Comment by walidabualafia** [comment]
Yes, XFCE desktop works perfectly.

We've been getting around the MATLAB issues by launching it from a terminal in XFCE Desktop.

**Comment by walidabualafia** [comment]
I just built a Schrodinger Maestro app, inspired by `SJTU-HPC/bc_relion`. The script is mostly the same as Matlab. I'm having the same issue there as well.

**Comment by walidabualafia** [comment]
This is due to RHEL8, turns out. Found the solution in discourse: https://discourse.openondemand.org/t/problems-with-interactive-matlab-app-window/2476

Thank you! :smile:
